export const CD_FLOOR_PRIMARY = 0.12;
export const CD_FLOOR_SECONDARY = 1.0;
export const CD_FLOOR_Q = 2.0;
export const CD_FLOORS = [CD_FLOOR_PRIMARY, CD_FLOOR_SECONDARY, CD_FLOOR_Q, 0];

export const COMBAT = {
  FURY_DAMAGE_MULT: 1.5,
  FURY_LIFESTEAL: 0.05,
  MOMENTUM_CAP: 0.2,
  MOMENTUM_DIVISOR: 1000,
  ULT_CHARGE_HIT: 3,
  ULT_CHARGE_KILL: 8,
  ULT_THRESHOLD: 100,
  ULT_THRESHOLD_OVERFLOW: 200,
  KNOCKBACK_FORCE: 300,
  SPLITTER_DMG_MULT: 0.5,
  SPLITTER_ANGLE: 0.8,
  CHAIN_DMG_MULT: 0.5,
  BULWARK_DMG_MULT: 0.75,
  BASTION_ALLY_DR_MULT: 0.8,
  ARCANIST_ECHO_CHANCE: 0.25,
  COMBO_STUN_DURATION: 0.5,
  WARLOCK_MANA_REFUND: 0.3,
  THORNS_PARTICLE_LIFE: 0.3,
  MONK_DODGE_CHANCE: 0.25,
  SPLIT_SHOT_SIDE_DAMAGE_MULT: 0.6,
  DAMAGE_CAP: 8,
  BOSS_DMG_REDUCTION_MULT: 0.5,
  BOSS_DMG_REDUCTION_DURATION: 3,
  BOSS_DMG_REDUCTION_HP_THRESHOLD: 0.5,
  BOSS_DMG_REDUCTION_MIN_WAVE: 15,
  BONUS_DMG_SOFT_CAP_THRESHOLD: 8,
  BONUS_DMG_SOFT_CAP_KNEE: 6,
  BLOODLUST_SPEED_CAP: 1.0,
  BLOODLUST_CRIT_CAP: 0.15,
  ELITE_WAVE_THRESHOLD: 13,
  ELITE_WAVE2_THRESHOLD: 17,
  ELITE_CHANCE: 0.1,
  ELITE_CHANCE_WAVE2: 0.2,
  ELITE_HP_MULT: 2.5,
  ELITE_DMG_MULT: 1.3,
  ELITE_XP_MULT: 2,
  BACKSTAB_ANGLE: Math.PI / 4,
  PROXIMITY_AURA_TICK_RATE: 0.5,
} as const;

export const TIMING = {
  IFRAME_DASH: 0.2,
  IFRAME_SPLIT: 0.3,
  IFRAME_BLOCK: 0.3,
  IFRAME_DAMAGE: 0.4,
  IFRAME_RESPAWN: 1.5,
  IFRAME_MONK_ULT: 0.8,
  IFRAME_SHIELD_WALL: 1.5,
  IFRAME_ENEMY_HIT: 0.1,
  IFRAME_BLINK: 0.3,
  IFRAME_LEAP: 0.3,
  IFRAME_LIVES_RESPAWN: 3.0,
  DEATH_TIMER: 1.0,
  HIT_FLASH: 0.3,
  FLASH_SCREEN: 0.3,
  FLASH_SCREEN_BOSS: 0.2,
  FLASH_SCREEN_ULT: 0.3,
  ANIM_CAST: 0.35,
  ANIM_ATTACK: 0.8,
  ANIM_ATTACK_WIND: 0.2,
  ANIM_ULT: 0.8,
  ZONE_TICK: 0.5,
  BURN_TICK: 0.5,
  AURA_HEAL_TICK: 0.5,
  METEOR_DELAY_STEP: 0.25,
  BEAM_LIFE: 0.25,
  SPELL_DEFAULT_DELAY: 0.5,
  STUN_DURATION: 0.5,
  FREEZE_DURATION: 1.5,
  STORM_SHIELD_TIME: 1.0,
  PARTICLE_LIFE_SHORT: 0.3,
  PARTICLE_LIFE_MEDIUM: 0.5,
  PARTICLE_LIFE_LONG: 0.8,
  HIT_PARTICLE_SCALE: 0.5,
  SPAWN_PARTICLE_SCALE: 1.5,
} as const;

export const RANGES = {
  AURA: 120,
  CHAIN: 120,
  CHAIN_ULT: 200,
  DASH_DISTANCE: 120,
  SHOCKWAVE: 120,
  STORM_SHIELD: 120,
  MAGNET_PULL: 300,
} as const;

export const ENEMY_AI = {
  ENRAGE_MULT: 1.5,
  KITING_SLOW: 0.8,
  BACK_AWAY_SLOW: 0.6,
  SLOW_MULT: 0.4,
  TRAIL_SPAWN_CHANCE: 0.5,
} as const;

export const DUNGEON_TIMING = {
  REWIND_SNAPSHOT_INTERVAL: 3,
  WAVE_SPAWN_TIMER: 1.5,
  TRICKLE_SPEED_SCALE: 0.02,
  BOSS_MINION_SPAWN_DURATION: 10,
} as const;

export const MAX_PARTICLES = 200;
export const MAX_SHOCKWAVES = 50;
export const MAX_FLOATING_TEXTS = 50;
export const MAX_TRAILS = 300;
export const MAX_SPELLS = 128;
export const MAX_EPROJ = 64;
export const MAX_ZONES = 32;
export const MAX_AOE_MARKERS = 32;
export const MAX_BEAMS = 64;

export const WAVE_PHYSICS = {
  BOOMERANG_RETURN: 0.5,
  MAX_BOUNCES: 3,
  TRAIL_CHANCE: 0.3,
  TRAIL_PARTICLE_SCALE: 0.5,
  CHAIN_RANGE: 120,
  FROZEN_TOUCH_CHANCE: 0.25,
  EXPLOSION_SHOCKWAVE_SCALE: 0.7,
  EXPLOSION_PARTICLE_SCALE: 1.5,
  MAGIC_EXPLOSION_SHOCKWAVE: 0.8,
  HIT_PARTICLE_LIFE: 0.3,
  ZONE_HIT_PARTICLE_LIFE: 0.6,
  SPLIT_SHOT_ANGLE: 0.26,
  SLOW_MOVE_MULT: 0.5,
} as const;

/** Logarithmic diminishing returns for flat stackable upgrades.
 *  Stacks 1-3: full value. Stack 4+: ln(4)/ln(stacks+1) multiplier. */
export function flatScaling(baseValue: number, stacks: number): number {
  if (stacks <= 3) return baseValue;
  return baseValue * Math.log(4) / Math.log(stacks + 1);
}

/** Hyperbolic soft cap for total flat bonus damage. */
export function softCapBonusDmg(rawBonus: number): number {
  if (rawBonus <= COMBAT.BONUS_DMG_SOFT_CAP_THRESHOLD) return rawBonus;
  const excess = rawBonus - COMBAT.BONUS_DMG_SOFT_CAP_THRESHOLD;
  const knee = COMBAT.BONUS_DMG_SOFT_CAP_KNEE;
  return COMBAT.BONUS_DMG_SOFT_CAP_THRESHOLD + excess / (1 + excess / knee);
}
