import { ClassDefInput, SpellType } from '../types';

export const CLASSES: Record<string, ClassDefInput> = {
  pyromancer: {
    name: 'Pyromancer', color: '#ff6633', glow: '#ff4400',
    desc: 'Fire mastery. High burst damage.',
    hp: 7, moveSpeed: 185, maxMana: 100, manaRegen: 14,
    passive: { name: 'Ignite', desc: 'Enemies hit burn for 4 dmg over 2s' },
    spells: [
      { name: 'Fireball', key: 'LMB', type: SpellType.Projectile, dmg: 2, speed: 400, radius: 10, mana: 10, cd: 0.35, life: 1.2, explode: 50, color: '#ff6633', trail: '#ff3300', burn: 2 },
      { name: 'Flame Wave', key: 'RMB', type: SpellType.Cone, dmg: 2, range: 110, mana: 22, cd: 2.5, angle: 0.8, color: '#ff4400' },
      { name: 'Meteor', key: 'Q', type: SpellType.AoeDelayed, dmg: 4, mana: 32, cd: 7, delay: 0.8, radius: 75, color: '#ff2200' },
      { name: 'Inferno', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#ff2200', mana: 0, cd: 0 },
    ],
  },
  cryomancer: {
    name: 'Cryomancer', color: '#44bbff', glow: '#2288dd',
    desc: 'Ice magic. Crowd control.',
    hp: 7, moveSpeed: 185, maxMana: 100, manaRegen: 14,
    passive: { name: 'Frostbite', desc: 'Slowed enemies take +1 damage' },
    spells: [
      { name: 'Frost Ray', key: 'LMB', type: SpellType.Beam, dmg: 1.2, range: 250, mana: 6, cd: 0.2, width: 4, slow: 1.0, color: '#88ddff', trail: '#44aadd', applyMark: { name: 'frost', duration: 3.0, maxStacks: 3, visual: '#88CCFF' } },
      { name: 'Freeze Breath', key: 'RMB', type: SpellType.Cone, dmg: 2, range: 120, mana: 22, cd: 3.5, angle: 0.7, slow: 1.5, color: '#88ddff', detonateMark: { name: 'frost', dmgPerStack: 2.0, aoeOnDetonate: 60, spreadOnDetonate: true, effectOnDetonate: { stun: 0.3 } } },
      { name: 'Blizzard', key: 'Q', type: SpellType.Zone, dmg: 1, mana: 28, cd: 8, radius: 90, duration: 4, tickRate: 0.7, slow: 0.8, color: '#2288dd' },
      { name: 'Absolute Zero', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#2288dd', mana: 0, cd: 0 },
    ],
  },
  stormcaller: {
    name: 'Stormcaller', color: '#bb66ff', glow: '#9944dd',
    desc: 'Channeled lightning. Static Charge resource.',
    hp: 7, moveSpeed: 190, maxMana: 100, manaRegen: 2,
    passive: { name: 'Feedback Loop', desc: 'Auto-detonations refund 0.3s of Storm Step cd and build +5% channel damage (caps at +50%)' },
    spells: [
      { name: 'Lightning', key: 'LMB', type: SpellType.Beam, dmg: 1, range: 320, mana: 0, cd: 0.28, width: 3, color: '#cc88ff', trail: '#aa55ff', channel: 1.5, channelSlow: 0.5, channelScale: 2.5, channelBreak: 3, applyMark: { name: 'static', duration: 4.0, maxStacks: 3, visual: '#cc88ff' } },
      { name: 'Discharge', key: 'RMB', type: SpellType.Nova, dmg: 10, mana: 50, cd: 5, range: 180, color: '#cc88ff', stun: 2.0, channel: 2.5, channelSlow: 0.6, channelBreak: 5, detonateMark: { name: 'static', dmgPerStack: 3.0, effectOnDetonate: { stun: 0.5 } } },
      { name: 'Storm Step', key: 'Q', type: SpellType.Blink, range: 180, mana: 25, cd: 2.5, color: '#bb66ff' },
      { name: 'Thunder God', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#ffcc44', mana: 0, cd: 0 },
    ],
  },
  arcanist: {
    name: 'Arcanist', color: '#ff55aa', glow: '#dd3388',
    desc: 'Arcane arts. Mobility & homing.',
    hp: 7, moveSpeed: 195, maxMana: 90, manaRegen: 13,
    passive: { name: 'Arcane Echo', desc: 'Hits have 25% chance to echo your primary attack' },
    spells: [
      { name: 'Arcane Bolt', key: 'LMB', type: SpellType.Homing, dmg: 1.5, speed: 300, radius: 8, mana: 7, cd: 0.28, life: 2, homing: 2.5, color: '#ff55aa', trail: '#dd3388' },
      { name: 'Blink', key: 'RMB', type: SpellType.Blink, range: 170, mana: 18, cd: 2.5, color: '#ff88cc' },
      { name: 'Barrage', key: 'Q', type: SpellType.Barrage, dmg: 1, speed: 380, radius: 7, mana: 35, cd: 7, count: 7, spread: 0.4, life: 1.2, color: '#ff55aa', trail: '#cc2277' },
      { name: 'Arcane Storm', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#ff55aa', mana: 0, cd: 0 },
    ],
  },
  necromancer: {
    name: 'Necromancer', color: '#55cc55', glow: '#228822',
    desc: 'Death magic. Drains life.',
    hp: 8, moveSpeed: 180, maxMana: 100, manaRegen: 14,
    passive: { name: 'Soul Harvest', desc: 'Kills heal 0.5 HP' },
    spells: [
      { name: 'Soul Bolt', key: 'LMB', type: SpellType.Projectile, dmg: 1.5, speed: 360, radius: 9, mana: 8, cd: 0.35, life: 1.2, color: '#55cc55', trail: '#228822', drain: 0.5 },
      { name: 'Life Siphon', key: 'RMB', type: SpellType.Tether, dmg: 0, mana: 22, cd: 6, color: '#44aa44', trail: '#228822', tetherRange: 180, tetherDmg: 1.5, tetherHeal: 1.0, tetherTickRate: 0.3, tetherDuration: 3, tetherReward: { dmgBurst: 3, healBurst: 2 } },
      { name: 'Plague', key: 'Q', type: SpellType.Zone, dmg: 1, mana: 32, cd: 8, radius: 80, duration: 4, tickRate: 0.8, slow: 0.3, color: '#338833' },
      { name: 'Army of Dead', key: 'Space', type: SpellType.Ultimate, ultCharge: 110, color: '#228822', mana: 0, cd: 0 },
    ],
  },
  chronomancer: {
    name: 'Chronomancer', color: '#ffcc44', glow: '#cc9922',
    desc: 'Time magic. Haste & slow.',
    hp: 6, moveSpeed: 195, maxMana: 110, manaRegen: 16,
    passive: { name: 'Haste Aura', desc: '+15% move speed for nearby ally' },
    spells: [
      { name: 'Time Bolt', key: 'LMB', type: SpellType.Projectile, dmg: 2, speed: 480, radius: 8, mana: 8, cd: 0.35, life: 1, stun: 0.3, color: '#ffcc44', trail: '#cc9922' },
      { name: 'Temporal Field', key: 'RMB', type: SpellType.Zone, dmg: 0, mana: 22, cd: 4, radius: 70, duration: 3.5, tickRate: 0.5, slow: 2.5, stun: 0.3, color: '#ffdd66' },
      { name: 'Temporal Tether', key: 'Q', type: SpellType.Tether, dmg: 0, mana: 30, cd: 10, color: '#ffcc44', trail: '#cc9922', tetherRange: 200, tetherDmg: 0, tetherTickRate: 0.5, tetherDuration: 4, tetherReward: { stun: 2.5 } },
      { name: 'Time Stop', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#ffdd66', mana: 0, cd: 0 },
    ],
  },
  knight: {
    name: 'Knight', color: '#aabbcc', glow: '#778899',
    desc: 'Tank. Absorbs damage, protects ally.',
    hp: 12, moveSpeed: 170, maxMana: 80, manaRegen: 12,
    passive: { name: 'Bulwark', desc: 'Take 25% less damage' },
    spells: [
      { name: 'Shield Throw', key: 'LMB', type: SpellType.Projectile, dmg: 2, speed: 350, radius: 10, mana: 4, cd: 0.4, life: 0.8, color: '#ccddee', trail: '#8899aa', pierce: 1 },
      { name: 'Shield Combo', key: 'RMB', type: SpellType.Leap, range: 100, mana: 15, cd: 2, dmg: 1.5, aoeR: 60, slow: 0.5, color: '#8899aa',
        combo: { steps: 2, timeout: 2.0, dmgScale: [1.0, 2.0], effects: { 2: { stun: 1.0 } } } },
      { name: 'Charge', key: 'Q', type: SpellType.Blink, range: 200, mana: 20, cd: 3.5, color: '#aabbcc' },
      { name: 'Shield Wall', key: 'Space', type: SpellType.Ultimate, ultCharge: 120, color: '#ccddee', mana: 0, cd: 0 },
    ],
  },
  berserker: {
    name: 'Berserker', color: '#ff4444', glow: '#cc2222',
    desc: 'Melee DPS. The lower the HP, the stronger.',
    hp: 14, moveSpeed: 200, maxMana: 70, manaRegen: 10,
    passive: { name: 'Fury', desc: 'Below 50% HP: +50% damage and speed, 5% lifesteal. Close enemies take 1 dps and you deal +30% damage', proximityBonus: { range: 80, dmgMult: 1.3, aura: 1.0 } },
    spells: [
      { name: 'Axe Combo', key: 'LMB', type: SpellType.Cone, dmg: 2.5, range: 50, mana: 2, cd: 0.35, angle: 1.5, color: '#ff6644',
        combo: { steps: 3, timeout: 2.0, dmgScale: [1.0, 1.2, 2.0], effects: { 3: { aoeR: 50 } } } },
      { name: 'Throwing Axe', key: 'RMB', type: SpellType.Projectile, dmg: 3, speed: 500, radius: 10, mana: 8, cd: 0.8, life: 1.2, color: '#ff4444', trail: '#cc2222' },
      { name: 'Leap Slam', key: 'Q', type: SpellType.Leap, range: 180, mana: 20, cd: 3.5, dmg: 3, aoeR: 60, color: '#ff3322' },
      { name: 'Blood Rage', key: 'Space', type: SpellType.Ultimate, ultCharge: 80, color: '#ff2222', mana: 0, cd: 0 },
    ],
  },
  paladin: {
    name: 'Paladin', color: '#ffddaa', glow: '#ccaa66',
    desc: 'Support. Heals ally, smites undead.',
    hp: 10, moveSpeed: 180, maxMana: 120, manaRegen: 16,
    passive: { name: 'Aura of Light', desc: 'Nearby ally regens 2 HP/s' },
    spells: [
      { name: 'Smite', key: 'LMB', type: SpellType.Projectile, dmg: 2, speed: 380, radius: 9, mana: 7, cd: 0.35, life: 1.2, color: '#ffddaa', trail: '#ccaa66', explode: 25, applyMark: { name: 'judgment', duration: 3.0, maxStacks: 1, visual: '#ffddaa' } },
      { name: 'Holy Shield', key: 'RMB', type: SpellType.AllyShield, mana: 25, cd: 5, duration: 3, color: '#ffffcc' },
      { name: 'Consecrate', key: 'Q', type: SpellType.Zone, dmg: 2, mana: 24, cd: 7, radius: 100, duration: 3, tickRate: 0.6, slow: 0.3, color: '#ffeeaa', heal: 2, detonateMark: { name: 'judgment', dmgPerStack: 3.0, aoeOnDetonate: 100, effectOnDetonate: { heal: 1.5 } } },
      { name: 'Holy Light', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#ffffcc', mana: 0, cd: 0 },
    ],
  },
  ranger: {
    name: 'Ranger', color: '#88cc44', glow: '#668833',
    desc: 'Ranged DPS. Fast attacks, high mobility.',
    hp: 6, moveSpeed: 200, maxMana: 90, manaRegen: 14,
    passive: { name: 'Eagle Eye', desc: 'Primary range +40%. Consecutive Arrow hits build Focus — 3rd+ hit crits' },
    spells: [
      { name: 'Power Shot', key: 'LMB', type: SpellType.Projectile, dmg: 1.5, speed: 600, radius: 5, mana: 4, cd: 0.8, life: 1.8, pierce: 2, color: '#88cc44', trail: '#668833',
        chargeTime: 1.2, chargeSlow: 0.5, chargeMinDmg: 0.5, chargeMaxDmg: 4.5, chargePierce: 2, positionBonus: { type: 'pillar', mult: 1.5, pillarRange: 100 } },
      { name: 'Volley', key: 'RMB', type: SpellType.Barrage, dmg: 1, speed: 500, radius: 5, mana: 18, cd: 2.5, count: 4, spread: 0.6, life: 1, color: '#88cc44', trail: '#556622' },
      { name: 'Trap', key: 'Q', type: SpellType.Trap, mana: 15, cd: 4, dmg: 3, radius: 50, slow: 2, color: '#aadd55' },
      { name: 'Arrow Rain', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#88cc44', mana: 0, cd: 0 },
    ],
  },
  druid: {
    name: 'Druid', color: '#44aa33', glow: '#337722',
    desc: 'Nature magic. Summons + heals.',
    hp: 9, moveSpeed: 185, maxMana: 100, manaRegen: 14,
    passive: { name: 'Regrowth', desc: 'Regen 1 HP every 7 seconds' },
    spells: [
      { name: 'Thorn Swipe', key: 'LMB', type: SpellType.Cone, dmg: 1.5, range: 80, mana: 4, cd: 0.32, angle: 1.0, slow: 0.4, color: '#44aa33' },
      { name: 'Entangle', key: 'RMB', type: SpellType.Zone, dmg: 0, mana: 20, cd: 5, radius: 60, duration: 2, tickRate: 0.5, stun: 2, color: '#66bb44' },
      { name: 'Spirit Wolf', key: 'Q', type: SpellType.Ultimate, ultCharge: 0, mana: 30, cd: 10, color: '#88aa55' },
      { name: "Nature's Wrath", key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#33aa22', mana: 0, cd: 0 },
    ],
  },
  warlock: {
    name: 'Warlock', color: '#8833aa', glow: '#662288',
    desc: 'Dark magic. High risk, high reward.',
    hp: 6, moveSpeed: 175, maxMana: 120, manaRegen: 18,
    passive: { name: 'Dark Pact', desc: 'Casting refunds 30% mana but costs 1 HP' },
    spells: [
      { name: 'Shadow Bolt', key: 'LMB', type: SpellType.Projectile, dmg: 3, speed: 260, radius: 10, mana: 10, cd: 0.5, life: 1.5, color: '#8833aa', trail: '#662288',
        chargeTime: 0.8, chargeSlow: 0.5, chargeMinDmg: 1.5, chargeMaxDmg: 6.0, chargeRadius: 30 },
      { name: 'Drain Life', key: 'RMB', type: SpellType.Beam, dmg: 2, range: 200, mana: 18, cd: 1, width: 4, drain: 2, color: '#aa44cc' },
      { name: 'Summon Imp', key: 'Q', type: SpellType.Ultimate, ultCharge: 0, mana: 25, cd: 8, color: '#cc4466' },
      { name: 'Doom', key: 'Space', type: SpellType.Ultimate, ultCharge: 90, color: '#662288', mana: 0, cd: 0 },
    ],
  },
  monk: {
    name: 'Monk', color: '#eedd88', glow: '#ccaa44',
    desc: 'Martial arts. Fast melee + dodging.',
    hp: 7, moveSpeed: 210, maxMana: 80, manaRegen: 12,
    passive: { name: 'Inner Peace', desc: '25% chance to dodge attacks. +50% damage from behind enemies', backstab: 1.5 },
    spells: [
      { name: 'Chi Combo', key: 'LMB', type: SpellType.Cone, dmg: 1, range: 60, mana: 3, cd: 0.2, angle: 1.2, color: '#eedd88',
        combo: { steps: 3, timeout: 1.5, dmgScale: [0.8, 1.2, 2.5], effects: { 3: { stun: 0.5, aoeR: 40 } } } },
      { name: 'Flying Kick', key: 'RMB', type: SpellType.Leap, range: 180, mana: 12, cd: 2, dmg: 4, aoeR: 55, color: '#ccaa44' },
      { name: 'Chi Burst', key: 'Q', type: SpellType.Zone, dmg: 0, mana: 15, cd: 6, radius: 40, duration: 3, tickRate: 0.8, heal: 2, color: '#ffffcc' },
      { name: 'Thousand Fists', key: 'Space', type: SpellType.Ultimate, ultCharge: 80, color: '#eedd88', mana: 0, cd: 0 },
    ],
  },
  engineer: {
    name: 'Engineer', color: '#dd8833', glow: '#aa6622',
    desc: 'Builds turrets and gadgets.',
    hp: 9, moveSpeed: 175, maxMana: 100, manaRegen: 14,
    passive: { name: 'Overclock', desc: 'Turrets fire 20% faster' },
    spells: [
      { name: 'Wrench Throw', key: 'LMB', type: SpellType.Projectile, dmg: 1.5, speed: 350, radius: 7, mana: 5, cd: 0.3, life: 1.0, color: '#dd8833', trail: '#aa6622', homing: 1.0 },
      { name: 'Deploy Turret', key: 'RMB', type: SpellType.Zone, dmg: 1, mana: 25, cd: 6, radius: 120, duration: 15, tickRate: 0.8, color: '#cc7722' },
      { name: 'Mine Field', key: 'Q', type: SpellType.Trap, mana: 20, cd: 5, dmg: 4, radius: 45, count: 3, spread: 0.8, color: '#ffaa33' },
      { name: 'Mega Turret', key: 'Space', type: SpellType.Ultimate, ultCharge: 120, color: '#dd8833', mana: 0, cd: 0 },
    ],
  },
  graviturge: {
    name: 'Graviturge', color: '#6644aa', glow: '#4422aa',
    desc: 'Gravity magic. Proximity aura + sustain.',
    passive: { name: 'Gravity Well', desc: 'Enemies within 80 units take 0.5 dps; each nearby enemy grants +1 mana/s' },
    spells: [
      { name: 'Gravity Bolt', key: 'LMB', type: SpellType.Projectile, dmg: 1.5, speed: 280, radius: 10, mana: 6, cd: 0.32, life: 0.8, slow: 0.5, color: '#6644aa', trail: '#4422aa' },
      { name: 'Singularity', key: 'RMB', type: SpellType.Zone, dmg: 1.5, mana: 22, cd: 5, radius: 80, duration: 4, tickRate: 0.6, slow: 0.8, color: '#5533aa' },
      { name: 'Event Horizon', key: 'Q', type: SpellType.Tether, dmg: 0, mana: 22, cd: 8, color: '#7755cc', trail: '#4422aa', tetherRange: 200, tetherDmg: 2.0, tetherHeal: 1.0, tetherTickRate: 0.3, tetherDuration: 3, tetherReward: { stun: 2.0, dmgBurst: 3, healBurst: 2 } },
      { name: 'Gravitational Ruin', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#4422aa', mana: 0, cd: 0 },
    ],
  },
  bladecaller: {
    name: 'Bladecaller', color: '#cc3355', glow: '#aa2244',
    desc: 'Blade dancer. Kill-chain mobility.',
    passive: { name: 'Kill Rush', desc: 'Kills within 1.5s of Shadow Step reset its cooldown; kills grant +10% speed for 3s. 2x backstab damage', backstab: 2.0 },
    spells: [
      { name: 'Blade Chain', key: 'LMB', type: SpellType.Cone, dmg: 2.5, range: 55, mana: 3, cd: 0.3, angle: 1.2, color: '#cc3355',
        combo: { steps: 4, timeout: 1.8, dmgScale: [0.8, 1.0, 1.5, 3.0], effects: { 4: { aoeR: 60, stun: 0.3 } } } },
      { name: 'Shadow Step', key: 'RMB', type: SpellType.Leap, range: 140, mana: 12, cd: 2.5, dmg: 2, aoeR: 45, color: '#aa2244' },
      { name: 'Blade Toss', key: 'Q', type: SpellType.Barrage, dmg: 1.5, speed: 450, radius: 6, mana: 20, cd: 6, count: 5, spread: 0.5, life: 0.8, color: '#cc3355', trail: '#881133' },
      { name: 'Thousand Cuts', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#aa2244', mana: 0, cd: 0 },
    ],
  },
  architect: {
    name: 'Architect', color: '#44aacc', glow: '#228899',
    desc: 'Zone control. Constructs + fortification.',
    passive: { name: 'Fortification', desc: 'Take 20% less damage and +1 mana/s while near own zones' },
    spells: [
      { name: 'Arcane Bolt', key: 'LMB', type: SpellType.Homing, dmg: 1.5, speed: 320, radius: 7, mana: 5, cd: 0.28, life: 1.5, homing: 2.0, color: '#44aacc', trail: '#228899' },
      { name: 'Deploy Construct', key: 'RMB', type: SpellType.Zone, dmg: 1, mana: 24, cd: 6, radius: 100, duration: 12, tickRate: 0.9, slow: 0.3, color: '#339dbb' },
      { name: 'Scatter Mines', key: 'Q', type: SpellType.Trap, mana: 25, cd: 7, dmg: 3, radius: 40, count: 4, spread: 1.0, slow: 1.5, color: '#55ccdd' },
      { name: 'Mega Construct', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#228899', mana: 0, cd: 0 },
    ],
  },
  hexblade: {
    name: 'Hexblade', color: '#7755cc', glow: '#5533aa',
    desc: 'Stance-switching hybrid — ranged hexes, melee executions.',
    passive: { name: 'Hex Mastery', desc: 'Hex-marked enemies take 25% more damage from all sources; 3 stacks also slows 30%' },
    stanceForms: {
      formA: {
        name: 'Caster',
        color: '#a855f7',
        glow: '#7733cc',
        moveSpeed: 200,
        spells: [
          { name: 'Hex Bolt', key: 'LMB', type: SpellType.Projectile, dmg: 1.5, speed: 420, radius: 5, mana: 6, cd: 0.3, life: 0.8, homing: 0.8, color: '#a855f7', trail: '#7733cc' },
          { name: 'Doom Mark', key: 'RMB', type: SpellType.Homing, dmg: 0.5, speed: 500, radius: 6, mana: 12, cd: 3.0, life: 0.6, color: '#9966dd', trail: '#5533aa' },
          { name: 'Void Zone', key: 'Q', type: SpellType.Zone, dmg: 1, mana: 20, cd: 6, radius: 70, duration: 3, tickRate: 0.5, slow: 0.6, color: '#6644bb' },
        ],
      },
      formB: {
        name: 'Blade',
        color: '#dc2626',
        glow: '#aa1111',
        moveSpeed: 175,
        spells: [
          { name: 'Hex Slash', key: 'LMB', type: SpellType.Cone, dmg: 2.5, range: 55, mana: 2, cd: 0.25, angle: 1.5, color: '#dc2626' },
          { name: 'Shadow Leap', key: 'RMB', type: SpellType.AoeDelayed, dmg: 2, mana: 15, cd: 4, delay: 0.1, aoeR: 50, radius: 50, color: '#aa1111' },
          { name: 'Whirlwind', key: 'Q', type: SpellType.Nova, dmg: 3, mana: 18, cd: 5, radius: 60, color: '#ff3333' },
        ],
      },
      switchCd: 3.5,
      switchBuff: { duration: 1.0, dmgMult: 1.5, armor: 2 },
    },
    spells: [
      { name: 'Hex Bolt', key: 'LMB', type: SpellType.Projectile, dmg: 1.5, speed: 420, radius: 5, mana: 6, cd: 0.3, life: 0.8, homing: 0.8, color: '#a855f7', trail: '#7733cc' },
      { name: 'Doom Mark', key: 'RMB', type: SpellType.Homing, dmg: 0.5, speed: 500, radius: 6, mana: 12, cd: 3.0, life: 0.6, color: '#9966dd', trail: '#5533aa' },
      { name: 'Void Zone', key: 'Q', type: SpellType.Zone, dmg: 1, mana: 20, cd: 6, radius: 70, duration: 3, tickRate: 0.5, slow: 0.6, color: '#6644bb' },
      { name: 'Stance Switch', key: 'Space', type: SpellType.Ultimate, ultCharge: 0, color: '#5533aa', mana: 0, cd: 0 },
    ],
  },
  warden: {
    name: 'Warden', color: '#5588aa', glow: '#336688',
    desc: 'Shield tank. Body-blocks for allies.',
    passive: { name: 'Sentinel', desc: 'Take 20% less damage from enemies you face; melee attackers are marked for +1 ally damage' },
    spells: [
      { name: 'Guardian Strike', key: 'LMB', type: SpellType.Cone, dmg: 2.5, range: 60, mana: 4, cd: 0.4, angle: 1.0, color: '#5588aa' },
      { name: 'Bastion', key: 'RMB', type: SpellType.Zone, dmg: 0, mana: 20, cd: 5, radius: 70, duration: 3.5, tickRate: 0.5, slow: 0.5, color: '#6699bb' },
      { name: 'Aegis Link', key: 'Q', type: SpellType.AllyShield, mana: 25, cd: 8, duration: 4, color: '#88bbdd' },
      { name: 'Unbreakable', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#336688', mana: 0, cd: 0 },
    ],
  },
  cannoneer: {
    name: 'Cannoneer', color: '#aa7733', glow: '#885522',
    desc: 'Artillery. Slow power shots, long range.',
    hp: 9, moveSpeed: 170, maxMana: 90, manaRegen: 12,
    passive: { name: 'Heavy Caliber', desc: 'Every 4th shot deals 2x damage with double explosion radius' },
    spells: [
      { name: 'Power Shot', key: 'LMB', type: SpellType.Projectile, dmg: 3, speed: 500, radius: 11, mana: 10, cd: 0.5, life: 1.5, explode: 40, pierce: 1, color: '#aa7733', trail: '#885522',
        chargeTime: 1.0, chargeSlow: 0.4, chargeMinDmg: 1.0, chargeMaxDmg: 8.0, chargePierce: 1, chargeRadius: 25 },
      { name: 'Concussive Shell', key: 'RMB', type: SpellType.AoeDelayed, dmg: 2, mana: 18, cd: 3.5, delay: 0.4, radius: 60, stun: 0.8, color: '#cc9944' },
      { name: 'Caltrops', key: 'Q', type: SpellType.Trap, mana: 15, cd: 5, dmg: 2, radius: 55, slow: 2.5, count: 2, spread: 0.6, color: '#ddaa55' },
      { name: 'Artillery Barrage', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#885522', mana: 0, cd: 0 },
    ],
  },
  soulbinder: {
    name: 'Soulbinder', color: '#55aa88', glow: '#338866',
    desc: 'Soul mage. Marks + ally empowerment.',
    hp: 7, moveSpeed: 185, maxMana: 110, manaRegen: 15,
    passive: { name: 'Soul Bond', desc: 'LMB marks enemies for 4s; allies deal +1 damage and heal 0.5 HP on marked kills' },
    spells: [
      { name: 'Soul Lash', key: 'LMB', type: SpellType.Beam, dmg: 1.5, range: 220, mana: 6, cd: 0.28, width: 3, color: '#55aa88', trail: '#338866' },
      { name: 'Soul Tether', key: 'RMB', type: SpellType.Tether, dmg: 0, mana: 18, cd: 5, color: '#66bb99', trail: '#338866', tetherRange: 250, tetherDmg: 0, tetherTickRate: 0.4, tetherDuration: 2, tetherReward: { stun: 1.5 } },
      { name: 'Soul Surge', key: 'Q', type: SpellType.Zone, dmg: 0, mana: 30, cd: 8, radius: 80, duration: 4, tickRate: 0.8, heal: 1.5, color: '#44aa77' },
      { name: 'Soul Storm', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#338866', mana: 0, cd: 0 },
    ],
  },
  invoker: {
    name: 'Invoker', color: '#cc8844', glow: '#aa6622',
    desc: 'Elemental mastery. Multi-element combos.',
    hp: 7, moveSpeed: 190, maxMana: 100, manaRegen: 14,
    passive: { name: 'Elemental Attunement', desc: 'Burning+slowed enemies take +1 dmg/tick; stunned+burning enemies take 2x burn damage' },
    spells: [
      { name: 'Flame Bolt', key: 'LMB', type: SpellType.Projectile, dmg: 2, speed: 400, radius: 8, mana: 7, cd: 0.3, life: 1.1, burn: 2, color: '#cc8844', trail: '#aa6622' },
      { name: 'Frost Spike', key: 'RMB', type: SpellType.Projectile, dmg: 1.5, speed: 480, radius: 7, mana: 16, cd: 2, life: 1.0, slow: 1.5, pierce: 1, color: '#88ccee', trail: '#5599bb' },
      { name: 'Storm Strike', key: 'Q', type: SpellType.AoeDelayed, dmg: 3.5, mana: 35, cd: 9, delay: 0.7, radius: 70, stun: 0.8, color: '#ffcc44' },
      { name: 'Elemental Convergence', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#aa6622', mana: 0, cd: 0 },
    ],
  },
  tidecaller: {
    name: 'Tidecaller', color: '#3388bb', glow: '#226699',
    desc: 'Water mage. Summons + wave control.',
    hp: 8, moveSpeed: 180, maxMana: 100, manaRegen: 14,
    passive: { name: 'Rising Tide', desc: 'Each active summon grants +10% ability damage (max 3); 2+ summons enhance slow to 0.6s' },
    spells: [
      { name: 'Water Bolt', key: 'LMB', type: SpellType.Homing, dmg: 1.5, speed: 340, radius: 7, mana: 6, cd: 0.28, life: 1.8, homing: 2.5, color: '#3388bb', trail: '#226699' },
      { name: 'Tidal Wave', key: 'RMB', type: SpellType.Cone, dmg: 2, range: 130, mana: 22, cd: 3, angle: 0.9, slow: 1.5, color: '#44aadd' },
      { name: 'Summon Elemental', key: 'Q', type: SpellType.Ultimate, ultCharge: 0, mana: 35, cd: 10, color: '#55bbee' },
      { name: 'Tsunami', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#226699', mana: 0, cd: 0 },
    ],
  },
  voidweaver: {
    name: 'Voidweaver', color: '#aa44cc', glow: '#882299',
    desc: 'Void magic. Traps, zones, debuffs.',
    hp: 6, moveSpeed: 185, maxMana: 110, manaRegen: 16,
    passive: { name: 'Entropic Decay', desc: 'Debuffed enemies take 15% more damage from all sources; debuffed kills explode for 1 AOE damage' },
    spells: [
      { name: 'Void Bolt', key: 'LMB', type: SpellType.Projectile, dmg: 1.5, speed: 320, radius: 9, mana: 6, cd: 0.32, life: 1.2, burn: 3, slow: 0.4, color: '#aa44cc', trail: '#882299' },
      { name: 'Corruption Zone', key: 'RMB', type: SpellType.Zone, dmg: 1, mana: 22, cd: 4, radius: 90, duration: 5, tickRate: 0.6, slow: 1.0, color: '#9933bb' },
      { name: 'Void Traps', key: 'Q', type: SpellType.Trap, mana: 25, cd: 6, dmg: 3, radius: 50, count: 3, spread: 0.9, slow: 2.0, color: '#cc55ee' },
      { name: 'Void Rift', key: 'Space', type: SpellType.Ultimate, ultCharge: 100, color: '#882299', mana: 0, cd: 0 },
    ],
  },
};

export const CLASS_ORDER: string[] = [
  'pyromancer', 'cryomancer', 'stormcaller', 'arcanist', 'necromancer',
  'chronomancer', 'knight', 'berserker', 'paladin', 'ranger',
  'druid', 'warlock', 'monk', 'engineer',
  'graviturge', 'bladecaller', 'architect', 'hexblade', 'warden',
  'cannoneer', 'soulbinder', 'invoker', 'tidecaller', 'voidweaver',
];
